{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resume-service.fullname" . }}-secret
  namespace: {{ include "resume-service.namespace" . }}
  labels:
    {{- include "resume-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.dbPassword }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  {{- else }}
  DB_PASSWORD: {{ "changeme" | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.s3AccessKey }}
  S3_ACCESS_KEY: {{ .Values.secrets.s3AccessKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.s3SecretKey }}
  S3_SECRET_KEY: {{ .Values.secrets.s3SecretKey | b64enc | quote }}
  {{- end }}
stringData:
  DB_NAME: "hirehub_resumes"
  DB_USER: "resume_service"
