{{- if and .Values.enabled .Values.serviceMonitor.enabled }}
{{- if .Values.global }}
{{- if .Values.global.monitoring }}
{{- if .Values.global.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "notification-service.fullname" . }}
  namespace: {{ include "notification-service.namespace" . }}
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
    release: prometheus
spec:
  selector:
    matchLabels:
      {{- include "notification-service.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ include "notification-service.namespace" . }}
  endpoints:
    - port: metrics
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      honorLabels: true
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: 'go_.*'
          action: keep
        - sourceLabels: [__name__]
          regex: 'kafka_.*'
          action: keep
        - sourceLabels: [__name__]
          regex: 'notification_.*'
          action: keep
        - sourceLabels: [__name__]
          regex: 'hirehub_.*'
          action: keep
{{- end }}
{{- end }}
{{- end }}
{{- end }}
