apiVersion: v2
name: job-service
description: HireHub Job Service - Job posting management (Java/Spring Boot/gRPC)
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - job
  - posting
  - grpc
  - java
  - spring-boot

maintainers:
  - name: HireHub Team
    email: team@hirehub.io
