apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hirehub

resources:
  - namespace.yaml
  - service-account.yaml
  - network-policy.yaml
  - external-secrets.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: hirehub-platform
    includeSelectors: false
