apiVersion: v2
name: notification-service
description: HireHub Notification Service - Kafka-based notification processing (Go)
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - notification
  - kafka
  - messaging
  - grpc
  - go
  - keda

maintainers:
  - name: HireHub Team
    email: team@hirehub.io
