{{- if .Values.global.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "hirehub.namespace" . }}
  labels:
    {{- include "hirehub.labels" . | nindent 4 }}
    {{- include "hirehub.istioLabels" . | nindent 4 }}
  annotations:
    {{- include "hirehub.annotations" . | nindent 4 }}
{{- end }}
