{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "match-service.fullname" . }}-secret
  namespace: {{ include "match-service.namespace" . }}
  labels:
    {{- include "match-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.dbPassword }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  {{- else }}
  DB_PASSWORD: {{ "changeme" | b64enc | quote }}
  {{- end }}
stringData:
  DB_NAME: "hirehub_match"
  DB_USER: "match_service"
