{{- if and .Values.enabled .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "user-service.serviceAccountName" . }}
  namespace: {{ include "user-service.namespace" . }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
  annotations:
    {{- include "user-service.irsaAnnotation" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
