apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .Values.nodePool.name }}
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values:
          {{- range .Values.ec2NodeClass.requirements.capacityTypes }}
            - {{ . }}
          {{- end }}
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
          {{- range .Values.ec2NodeClass.requirements.instanceCategories }}
            - {{ . }}
          {{- end }}
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values:
          {{- range .Values.ec2NodeClass.requirements.instanceSizes }}
            - {{ . }}
          {{- end }}
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ .Values.ec2NodeClass.name }}
      expireAfter: 720h

  limits:
    cpu: {{ .Values.nodePool.limits.cpu }}
    memory: {{ .Values.nodePool.limits.memory }}

  disruption:
    consolidationPolicy: {{ .Values.nodePool.disruption.consolidationPolicy }}
    consolidateAfter: {{ .Values.nodePool.disruption.consolidateAfter }}
