apiVersion: v2
name: user-service
description: HireHub User Service - User management and authentication (Go/gRPC)
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - user
  - authentication
  - grpc
  - go

maintainers:
  - name: HireHub Team
    email: team@hirehub.io
